-intstyle "ise" -incremental -o "/media/sf_ASE/VHDL/Milo/moltiplicatore_B/Booth_testbench_isim_beh.exe" -prj "/media/sf_ASE/VHDL/Milo/moltiplicatore_B/Booth_testbench_beh.prj" "work.Booth_testbench" 
